# golangci-lint配置文件
run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: forge

  govet:
    check-shadowing: true
    enable-all: true

  lll:
    line-length: 120

  maligned:
    suggest-new: true

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

  revive:
    min-confidence: 0
    rules:
      - name: exported
        disabled: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - errcheck
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

issues:
  exclude-rules:
    # 忽略测试文件中的某些规则
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

    # 忽略main.go中的某些规则
    - path: cmd/main\.go
      linters:
        - gochecknoinits

  max-issues-per-linter: 0
  max-same-issues: 0